name: CoffeeLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  coffeelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cp install/package.json package.json

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install coffeelint --save-dev

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run CoffeeLint
        run: npm run lint:coffee
