name: CoffeeLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coffeelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run CoffeeLint
        run: npm run lint:coffee
